### PR TITLE
Pull #2 - finishing touches on portfolio

### PR DESCRIPTION
**Pull request by MWLangenhorst88**
Functionality for each view should work!

### CODE REVIEW

**Comment by LukeBillington** [comment]
Hey there, just a couple things, your source code from what I can tell looks great, just watch out, it appears the node_modules folder with your dependencies were committed, I suggest adding it to your .gitignore. Also, there's some merge conflicts with the readme and proPic.jpg, I suggest checking those out.

**Comment by LukeBillington** [comment]
One thing I didn't catch is you didn't instruct in your readme to install nodemon globally `npm install -g nodemon`. I didn't catch this earlier as I had it already installed, this will help a ton otherwise users get an error on start.

**Comment by MWLangenhorst88** [comment]
Ahh, glad you noticed that!

**Comment by LukeBillington** [comment]
Sorry, didn't catch one more thing, you can remove express and express-session from the readme as it's already in the install and make sure you add node as a dependency then too, even though you pretty much need node for npm :D Otherwise LGTM

**Comment by MWLangenhorst88** [comment]
Got that set up. Thanks!

**Pull request merged**
